"use client";
import Link from "next/link";
import { useState } from "react";
import { Icon } from "@/components/ui/icon";

const steps = ["Upload", "Review columns", "Review records", "Destination", "Complete"];
export function ImportWizard() {
  const [step, setStep] = useState(0); const [fileName, setFileName] = useState<string>();
  const next = () => setStep((value) => Math.min(value + 1, 4));
  return <><Link href="/students" className="back-link">← Students</Link><header className="page-heading"><div><h1>Import students</h1><p>Add records from an existing Excel masterlist.</p></div></header>
    <ol className="wizard-steps">{steps.map((label, index) => <li key={label} className={index === step ? "active" : index < step ? "complete" : ""}><span>{index < step ? <Icon name="check" /> : index + 1}</span>{label}</li>)}</ol>
    <section className="wizard-panel">
      {step === 0 ? <div className="upload-step"><Icon name="upload" /><h2>Drop an Excel file here</h2><p>or choose a file from your computer</p><label className="button button-secondary">Choose file<input type="file" accept=".xlsx" hidden onChange={(event) => setFileName(event.target.files?.[0]?.name ?? "Student_Master_Directory.xlsx")} /></label>{fileName ? <div className="selected-file"><Icon name="files" /><span><strong>{fileName}</strong><small>Student Directory · 157 records detected</small></span><button onClick={() => setFileName(undefined)} aria-label="Remove file"><Icon name="close" /></button></div> : <small>.xlsx supported</small>}</div> : null}
      {step === 1 ? <MappingStep /> : null}{step === 2 ? <ReviewStep /> : null}{step === 3 ? <DestinationStep /> : null}{step === 4 ? <CompleteStep /> : null}
      <div className="wizard-actions">{step > 0 && step < 4 ? <button className="button button-secondary" onClick={() => setStep(step - 1)}>Back</button> : <span />}{step < 4 ? <button className="button button-primary" disabled={step === 0 && !fileName} onClick={next}>{step === 3 ? "Import 157 students" : "Continue"}</button> : <Link href="/students" className="button button-primary">View students</Link>}</div>
    </section></>;
}
function MappingStep() { return <div><h2>Review columns</h2><p className="section-copy">Most fields were recognized. Review the marked mapping before continuing.</p><div className="mapping-table"><div><b>Excel column</b><b>TALA field</b></div>{[["LRN", "LRN"], ["NAME", "Full name"], ["BIRTHDAY", "Birthday"], ["BIRTHPLACE", "Birthplace"], ["GRADE", "Grade"], ["ADDRESS", "Address"]].map(([source, target], index) => <div key={source}><span>{source}</span><select defaultValue={target} className={index === 3 ? "needs-review" : ""}><option>{target}</option><option>Birthplace</option><option>Address</option></select></div>)}</div></div>; }
function ReviewStep() { return <div><h2>Review records</h2><p className="validation-summary"><span className="valid">148 ready</span><span className="warning-text">9 warnings</span><span>0 errors</span></p><table className="compact-table"><thead><tr><th>Row</th><th>Name</th><th>Grade</th><th>Status</th><th>Issue</th></tr></thead><tbody><tr><td>12</td><td>Ana Santos</td><td>Grade 6</td><td><span className="status status-active"><i />Ready</span></td><td>—</td></tr><tr><td>16</td><td>Ramon Flores</td><td>Grade 6</td><td><span className="status status-warning"><i />Warning</span></td><td>Existing learner. Record will be reused.</td></tr></tbody></table><p className="helper-callout"><Icon name="alert" />For errors, correct the source Excel file and upload it again. This keeps the import auditable.</p></div>; }
function DestinationStep() { return <div><h2>Choose destination</h2><p className="section-copy">All imported students will be enrolled in this section.</p><div className="form-grid three"><label>School year<select><option>2026–2027</option></select></label><label>Grade<select><option>Grade 6</option></select></label><label>Section<select><option>Rizal</option></select></label></div></div>; }
function CompleteStep() { return <div className="complete-step"><span className="complete-icon"><Icon name="check" /></span><h2>Import complete</h2><p>The student records are ready to review.</p><dl><div><dt>Rows processed</dt><dd>157</dd></div><div><dt>New students</dt><dd>145</dd></div><div><dt>Existing students reused</dt><dd>12</dd></div><div><dt>Enrollments created</dt><dd>157</dd></div></dl></div>; }
