"use client";

import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { useCurrentUser } from "@/components/auth/auth-context";
import { activateSchoolYear, createGrade, createSchoolYear, createSection, getGrades, getSchoolYears, getSections } from "@/features/students/students-api";
import type { Grade, SchoolYear, Section } from "@/features/students/types";

export function SchoolSetup() {
  const user = useCurrentUser(); const [years, setYears] = useState<SchoolYear[]>([]); const [grades, setGrades] = useState<Grade[]>([]); const [sections, setSections] = useState<Section[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const refresh = async () => { setLoading(true); try { const [nextYears, nextGrades, nextSections] = await Promise.all([getSchoolYears(), getGrades(), getSections()]); setYears(nextYears); setGrades(nextGrades); setSections(nextSections); setError(""); } catch { setError("School setup records could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { void Promise.resolve().then(refresh); }, []);
  if (user?.role !== "SUPER_ADMIN") return <Alert variant="destructive"><AlertTitle>Super Admin access required</AlertTitle><AlertDescription>Only the Super Admin can change school-wide setup records.</AlertDescription></Alert>;
  return <><header className="page-heading"><div><h1>School setup</h1><p>Set up the school years, grades, and sections used throughout TALA.</p></div></header>{error ? <Alert variant="destructive"><AlertTitle>Setup unavailable</AlertTitle><AlertDescription>{error}</AlertDescription></Alert> : null}{loading ? <div className="grid gap-5 lg:grid-cols-3"><Skeleton className="h-72" /><Skeleton className="h-72" /><Skeleton className="h-72" /></div> : <div className="grid gap-5 lg:grid-cols-3"><SchoolYears years={years} refresh={refresh} /><Grades grades={grades} refresh={refresh} /><Sections years={years} grades={grades} sections={sections} refresh={refresh} /></div>}</>;
}
function SchoolYears({ years, refresh }: { years: SchoolYear[]; refresh: () => Promise<void> }) { const [label, setLabel] = useState(""); const [busy, setBusy] = useState(false); const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!/^\d{4}-\d{4}$/.test(label)) return toast.error("Use the format YYYY-YYYY."); setBusy(true); try { await createSchoolYear(label); setLabel(""); await refresh(); toast.success("School year added"); } catch { toast.error("Could not add school year"); } finally { setBusy(false); } }; const activate = async (id: string) => { setBusy(true); try { await activateSchoolYear(id); await refresh(); toast.success("Active school year updated"); } catch { toast.error("Could not activate school year"); } finally { setBusy(false); } }; return <Card><CardHeader><CardTitle>School years</CardTitle><CardDescription>Only one school year is active at a time.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><form onSubmit={submit}><FieldGroup><Field><FieldLabel htmlFor="school-year">New school year</FieldLabel><Input id="school-year" value={label} onChange={(event) => setLabel(event.target.value)} placeholder="2027-2028" maxLength={9} /></Field><Button type="submit" disabled={busy}>Add school year</Button></FieldGroup></form><div className="flex flex-col gap-2">{years.map((year) => <div key={year.id} className="flex items-center justify-between gap-3"><span className="font-medium">{year.label}</span>{year.isActive ? <Badge>Active</Badge> : <Button size="sm" variant="outline" disabled={busy} onClick={() => void activate(year.id)}>Set active</Button>}</div>)}</div></CardContent></Card>; }
function Grades({ grades, refresh }: { grades: Grade[]; refresh: () => Promise<void> }) { const [name, setName] = useState(""); const [level, setLevel] = useState(""); const [busy, setBusy] = useState(false); const submit = async (event: React.FormEvent) => { event.preventDefault(); const numericLevel = Number(level); if (!name.trim() || !Number.isInteger(numericLevel) || numericLevel < 0) return toast.error("Enter a grade name and non-negative whole-number level."); setBusy(true); try { await createGrade(name.trim(), numericLevel); setName(""); setLevel(""); await refresh(); toast.success("Grade added"); } catch { toast.error("Could not add grade"); } finally { setBusy(false); } }; return <Card><CardHeader><CardTitle>Grades</CardTitle><CardDescription>Grade levels are shared across all school years.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><form onSubmit={submit}><FieldGroup><Field><FieldLabel htmlFor="grade-name">Grade name</FieldLabel><Input id="grade-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Grade 7" /></Field><Field><FieldLabel htmlFor="grade-level">Grade level</FieldLabel><Input id="grade-level" value={level} onChange={(event) => setLevel(event.target.value)} inputMode="numeric" placeholder="7" /></Field><Button type="submit" disabled={busy}>Add grade</Button></FieldGroup></form><div className="flex flex-col gap-2">{grades.map((grade) => <div key={grade.id} className="flex items-center justify-between"><span className="font-medium">{grade.name}</span><span className="text-muted-foreground">Level {grade.level}</span></div>)}</div></CardContent></Card>; }
function Sections({ years, grades, sections, refresh }: { years: SchoolYear[]; grades: Grade[]; sections: Section[]; refresh: () => Promise<void> }) { const activeYear = years.find((year) => year.isActive); const [name, setName] = useState(""); const [schoolYearId, setSchoolYearId] = useState(""); const [gradeId, setGradeId] = useState(""); const [busy, setBusy] = useState(false); const selectedYearId = schoolYearId || activeYear?.id || ""; const selectedSections = useMemo(() => sections.filter((section) => section.schoolYearId === selectedYearId), [sections, selectedYearId]); const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim() || !selectedYearId || !gradeId) return toast.error("Choose a school year, grade, and section name."); setBusy(true); try { await createSection(name.trim(), gradeId, selectedYearId); setName(""); await refresh(); toast.success("Section added"); } catch { toast.error("Could not add section"); } finally { setBusy(false); } }; return <Card><CardHeader><CardTitle>Sections</CardTitle><CardDescription>Each section belongs to one grade and school year.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><form onSubmit={submit}><FieldGroup><Field><FieldLabel htmlFor="section-year">School year</FieldLabel><select id="section-year" value={selectedYearId} onChange={(event) => setSchoolYearId(event.target.value)}><option value="">Choose school year</option>{years.map((year) => <option key={year.id} value={year.id}>{year.label}</option>)}</select></Field><Field><FieldLabel htmlFor="section-grade">Grade</FieldLabel><select id="section-grade" value={gradeId} onChange={(event) => setGradeId(event.target.value)}><option value="">Choose grade</option>{grades.map((grade) => <option key={grade.id} value={grade.id}>{grade.name}</option>)}</select></Field><Field><FieldLabel htmlFor="section-name">Section name</FieldLabel><Input id="section-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Rizal" /></Field><Button type="submit" disabled={busy}>Add section</Button></FieldGroup></form><div className="flex flex-col gap-2">{selectedSections.map((section) => <div key={section.id} className="flex items-center justify-between gap-3"><span className="font-medium">{section.name}</span><span className="text-muted-foreground">{section.grade.name}</span></div>)}{selectedYearId && selectedSections.length === 0 ? <p className="text-sm text-muted-foreground">No sections in this school year yet.</p> : null}</div></CardContent></Card>; }
