"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { getStudent } from "@/features/students/students-api";
import type { Enrollment, Student } from "@/features/students/types";

const date = (value?: string | null) => value ? new Intl.DateTimeFormat("en-PH", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)) : "—";
const name = (student: Student) => [student.firstName, student.middleName, student.lastName, student.suffix].filter(Boolean).join(" ");
const initials = (student: Student) => [student.firstName, student.lastName].map((part) => part[0]).join("");
function current(enrollments: Enrollment[]) { return enrollments.find((item) => item.schoolYear.isActive) ?? enrollments[0]; }

export function StudentProfile({ id }: { id: string }) {
  const [student, setStudent] = useState<Student>(); const [error, setError] = useState("");
  useEffect(() => { let cancelled = false; getStudent(id).then((value) => { if (!cancelled) setStudent(value); }).catch(() => !cancelled && setError("We could not load this student record. It may no longer be available.")); return () => { cancelled = true; }; }, [id]);
  if (error) return <><Link href="/students" className="back-link">← Students</Link><Alert variant="destructive"><AlertTitle>Student record unavailable</AlertTitle><AlertDescription>{error}</AlertDescription></Alert></>;
  if (!student) return <div className="flex flex-col gap-5"><Skeleton className="h-4 w-24" /><Skeleton className="h-36 w-full" /><Skeleton className="h-64 w-full" /></div>;
  const enrollment = current(student.enrollments);
  return <><Link href="/students" className="back-link">← Students</Link><header className="student-record-header"><span className="profile-tab tab-grade-6" /><div className="profile-photo profile-photo-placeholder" aria-label={`${name(student)} photo placeholder`}><span>{initials(student)}</span><small>No photo</small></div><div className="student-record-title"><p className="record-kicker">Student record</p><h1>{name(student)}</h1><div className="record-identifiers">{enrollment ? <><span>{enrollment.section.grade.name}</span><span>{enrollment.section.name}</span></> : <span>Not currently enrolled</span>}{student.lrn ? <span>LRN <b className="tabular">{student.lrn}</b></span> : null}</div></div><div className="record-header-actions">{enrollment ? <Badge variant="secondary">{enrollment.status}</Badge> : null}<Link href={`/students/${student.id}/edit`} className="button button-secondary">Edit student</Link></div></header>
    <Tabs defaultValue="overview"><TabsList variant="line" className="profile-tabs" aria-label="Student record sections"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="enrollment">Enrollment history</TabsTrigger><TabsTrigger value="files">Files</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger></TabsList><TabsContent value="overview"><Overview student={student} enrollment={enrollment} /></TabsContent><TabsContent value="enrollment"><EnrollmentHistory enrollments={student.enrollments} /></TabsContent><TabsContent value="files"><Placeholder title="Files" text="Private student files will be connected in a later phase." /></TabsContent><TabsContent value="activity"><Placeholder title="Activity" text="Record activity will be connected in a later phase." /></TabsContent></Tabs></>;
}

function Overview({ student, enrollment }: { student: Student; enrollment?: Enrollment }) { return <div className="record-detail-layout"><div className="record-detail-content"><section className="info-section personal-information"><h2>Personal information</h2><dl className="name-breakdown"><div><dt>First name</dt><dd>{student.firstName}</dd></div><div><dt>Middle name</dt><dd>{student.middleName ?? "—"}</dd></div><div><dt>Last name</dt><dd>{student.lastName}</dd></div><div><dt>Suffix</dt><dd>{student.suffix ?? "—"}</dd></div></dl><dl className="personal-details-grid"><div><dt>Birthday</dt><dd>{date(student.birthday)}</dd></div><div><dt>Birthplace</dt><dd>{student.birthplace ?? "—"}</dd></div><div><dt>Address</dt><dd>{student.address ?? "—"}</dd></div></dl></section><InfoSection title="Parent and guardian" items={[["Guardian", student.guardianName], ["Contact number", student.contactNumber], ["Father", student.fatherName], ["Mother", student.motherName]]} /><InfoSection title="Remarks" items={[["Notes", student.remarks ?? "—"]]} /></div><aside className="record-summary"><section><p className="record-kicker">Current enrollment</p>{enrollment ? <dl><div><dt>School year</dt><dd>{enrollment.schoolYear.label}</dd></div><div><dt>Grade</dt><dd>{enrollment.section.grade.name}</dd></div><div><dt>Section</dt><dd>{enrollment.section.name}</dd></div><div><dt>Adviser</dt><dd>—</dd></div><div><dt>Status</dt><dd><Badge variant="secondary">{enrollment.status}</Badge></dd></div></dl> : <p className="summary-note">—</p>}</section><section><p className="record-kicker">Record status</p><p className="summary-note">Last updated {date(student.updatedAt)}.</p></section></aside></div>; }
function EnrollmentHistory({ enrollments }: { enrollments: Enrollment[] }) { return <section className="tab-content"><div className="tab-content-heading"><div><h2>Enrollment history</h2><p>Placement is recorded separately from learner identity.</p></div></div><div className="table-shell"><table className="record-table enrollment-table"><thead><tr><th>School year</th><th>Grade</th><th>Section</th><th>Status</th><th>Date enrolled</th></tr></thead><tbody>{enrollments.map((enrollment) => <tr key={enrollment.id}><td>{enrollment.schoolYear.label}</td><td>{enrollment.section.grade.name}</td><td>{enrollment.section.name}</td><td><Badge variant="secondary">{enrollment.status}</Badge></td><td>{date(enrollment.dateEnrolled ?? enrollment.createdAt)}</td></tr>)}</tbody></table>{enrollments.length === 0 ? <div className="empty-state"><h2>No enrollment history</h2><p>This student does not yet have an enrollment record.</p></div> : null}</div></section>; }
function Placeholder({ title, text }: { title: string; text: string }) { return <section className="tab-content"><div className="tab-content-heading"><div><h2>{title}</h2><p>{text}</p></div></div></section>; }
function InfoSection({ title, items }: { title: string; items: [string, string | null][] }) { return <section className="info-section"><h2>{title}</h2><dl>{items.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value ?? "—"}</dd></div>)}</dl></section>; }
